ALTER TABLE Igrica ADD CONSTRAINT V_developer
FOREIGN KEY (ID_developera) REFERENCES Developer(ID_developera)
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Igrica ADD CONSTRAINT V_zanr
FOREIGN KEY (ID_zanr) REFERENCES Zanr(ID_zanra)
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Igrica ADD CONSTRAINT V_izdavac
FOREIGN KEY (ID_izdavac) REFERENCES Izdavac(ID_izdavaca)
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Igrica_Na_Listi ADD CONSTRAINT V_korisnik
FOREIGN KEY (ID_korisnika) REFERENCES Korisnik(ID_korisnika)
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE Igrica_Na_Listi ADD CONSTRAINT V_igrica
FOREIGN KEY (ID_igrice) REFERENCES Igrica(ID_igrice)
ON DELETE RESTRICT ON UPDATE CASCADE;
